name: Upload Glue Script to S3

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on
    paths:
      - Script1/**  # This assumes your script is in a folder named `script`
  workflow_dispatch:
    inputs:
      run_job:
        description: 'The name of the Glue script to upload'
        required: true
        default: run     

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Set this in GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Set this in GitHub Secrets
          aws-region: us-west-2  # Change to your desired region

      - name: Upload Glue Script to S3
        run: |
          aws s3 cp Script1/script1.py s3://testbucket94927/Scripts/script1.py
          aws s3 cp Script2/script2.py s3://testbucket94927/Scripts/script2.py

      - name: Update Glue Job with New Script
        run: |
          aws glue update-job --job-name test-job --job-update "{\"Command\": {\"Name\": \"glueetl\", \"ScriptLocation\": \"s3://testbucket94927/Scripts/script2.py\", \"PythonVersion\": \"3\"}, \"Role\": \"arn:aws:iam::022608205880:role/test-glue-job\", \"GlueVersion\": \"4.0\"}" --region us-east-1
